-- 013_comments.sql
-- In-database metadata comments explaining schema purpose and design constraints

-- 1. Master Tables Comments
COMMENT ON TABLE public.profiles IS 'User roles and profiles linked directly with Supabase/auth metadata.';
COMMENT ON COLUMN public.profiles.role IS 'User roles: Owner (Full view/write), Admin (Operational write), Warehouse (Ingress), Sales (Egress), Production (Batches), Finance (OpEx).';

COMMENT ON TABLE public.settings IS 'Global system settings. Only holds a single row representing current configuration.';
COMMENT ON COLUMN public.settings.default_transfer_price IS 'Default transfer price from Hulu (Farm) to Hilir (Warehouse/Production).';

COMMENT ON TABLE public.suppliers IS 'Supplier information for external purchase of duck eggs and materials.';
COMMENT ON TABLE public.customers IS 'Customer registry categorized by business scale (Tengkulak, Distributor, etc.).';
COMMENT ON COLUMN public.customers.type IS 'Scale classification used for custom price mapping and commercial tiers.';

-- 2. Inventory Tables Comments
COMMENT ON TABLE public.stock_states IS 'Live balance tracking for raw and salted eggs with automated weighted moving HPP calculation.';
COMMENT ON COLUMN public.stock_states.qty IS 'Current stock quantity in real-time.';
COMMENT ON COLUMN public.stock_states.avg_cost IS 'Moving average cost (HPP/COGS) computed using standard inventory formulas.';

COMMENT ON TABLE public.farm_production IS 'Daily duck egg harvests recorded from Hulu division.';
COMMENT ON COLUMN public.farm_production.transfer_price IS 'The price applied when transferring raw eggs to the Hilir division (or settings default).';

COMMENT ON TABLE public.raw_transactions IS 'Historical double-entry ledger for raw egg stock movements.';
COMMENT ON COLUMN public.raw_transactions.ref_id IS 'ID reference linking back to farm_production, supplier_purchase, or production_batch.';

COMMENT ON TABLE public.production_transactions IS 'Historical ledger for finished salted egg stock movements.';

-- 3. Production Tables Comments
COMMENT ON TABLE public.production_batches IS 'Production batch cycles representing egg salting and ripening stages (Pemeraman, Panen, Siap Dijual, Selesai).';
COMMENT ON COLUMN public.production_batches.raw_egg_cost IS 'Cost of raw eggs at batch initialization, based on current moving average.';
COMMENT ON COLUMN public.production_batches.cost_per_unit IS 'Calculated finished goods cost per unit (HPP) after summing raw eggs, salts, ash, packages, and labor.';

-- 4. Sales and Revenue Comments
COMMENT ON TABLE public.sales IS 'Customer sale transactions documenting quantity, revenue, and direct product COGS (for gross profit calculation).';
COMMENT ON COLUMN public.sales.cogs IS 'Calculated total cost of goods sold based on moving average at the moment of sale.';
COMMENT ON COLUMN public.sales.gross_profit IS 'Difference between revenue (excluding shipping) and COGS.';

-- 5. Finance and Audit Comments
COMMENT ON TABLE public.operational_costs IS 'Operational expenditures categorized by category.';
COMMENT ON TABLE public.activity_logs IS 'Application actions log generated by UI users.';
COMMENT ON TABLE public.audit_logs IS 'Strictly immutable trigger-generated system level ledger tracking database-wide data mutations.';
